import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'
import fs from 'fs'
import { IncomingMessage, ServerResponse } from 'http'

const ARTIFACTS_ROOT = path.resolve(__dirname, '../../artifacts')

function generatePreviewHTML(artifact: any): string {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${artifact.title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; background: #0f172a; color: #e2e8f0; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
    .card { background: #1e293b; border-radius: 16px; padding: 32px; max-width: 480px; box-shadow: 0 8px 32px rgba(0,0,0,.4); }
    h1 { font-size: 20px; margin-bottom: 8px; color: #38bdf8; }
    .badge { display: inline-block; background: #0ea5e9; color: #fff; font-size: 11px; padding: 2px 8px; border-radius: 99px; margin-bottom: 12px; }
    p { font-size: 14px; color: #94a3b8; line-height: 1.6; }
    .meta { margin-top: 16px; padding-top: 16px; border-top: 1px solid #334155; font-size: 12px; color: #64748b; }
    .placeholder { margin-top: 20px; background: #0f172a; border-radius: 8px; height: 180px; display: flex; align-items: center; justify-content: center; color: #475569; font-size: 13px; }
  </style>
</head>
<body>
  <div class="card">
    <span class="badge">${artifact.moduleName}</span>
    <h1>${artifact.title}</h1>
    <p>${artifact.description}</p>
    <div class="meta">
      Agent: ${artifact.agentName} | 奖励: ${artifact.reward} DREAM<br>
      完成时间: ${artifact.createdAt}
    </div>
    <div class="placeholder">页面预览区域（由 Agent 生成的前端组件渲染）</div>
  </div>
</body>
</html>`
}

function generateSourceTSX(artifact: any): string {
  const componentName = artifact.moduleName
    .replace(/[^a-zA-Z\u4e00-\u9fff]/g, '')
    .replace(/[\u4e00-\u9fff]/g, c => `_${c.charCodeAt(0).toString(16)}`)
    || 'GeneratedModule'

  return `// Generated by Agent ${artifact.agentName}
// Task: ${artifact.taskLabel}
// Module: ${artifact.moduleName}
// Reward: ${artifact.reward} DREAM

import React, { useState } from 'react'
import './${componentName}.css'

interface Props {
  data?: unknown
}

export const ${componentName}: React.FC<Props> = ({ data }) => {
  const [isLoading, setIsLoading] = useState(false)

  return (
    <section className="${componentName.toLowerCase()}">
      <header>
        <h2>${artifact.title}</h2>
        <p className="subtitle">${artifact.description}</p>
      </header>
      {isLoading ? (
        <div className="loading">加载中...</div>
      ) : (
        <div className="content">
          {/* Agent 生成的模块内容 */}
          <p>模块: ${artifact.moduleName}</p>
        </div>
      )}
    </section>
  )
}

export default ${componentName}
`
}

function generateVideoHTML(artifact: any): string {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${artifact.title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #020617; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; font-family: system-ui, sans-serif; color: #e2e8f0; }
    .stage { width: 320px; height: 200px; background: radial-gradient(circle at 50% 80%, #1e293b, #0f172a); border-radius: 12px; overflow: hidden; position: relative; box-shadow: 0 0 40px rgba(56, 189, 248, .15); }
    .star { position: absolute; width: 4px; height: 4px; background: #fbbf24; border-radius: 50%; animation: twinkle 1.5s ease-in-out infinite alternate; }
    .star:nth-child(1) { top: 20%; left: 30%; animation-delay: 0s; }
    .star:nth-child(2) { top: 15%; left: 60%; animation-delay: .3s; }
    .star:nth-child(3) { top: 35%; left: 80%; animation-delay: .6s; }
    .star:nth-child(4) { top: 10%; left: 45%; animation-delay: .9s; }
    .star:nth-child(5) { top: 25%; left: 15%; animation-delay: 1.2s; }
    .castle { position: absolute; bottom: 0; left: 50%; transform: translateX(-50%); width: 120px; height: 80px; }
    .castle .tower { position: absolute; bottom: 0; width: 24px; background: linear-gradient(to top, #4338ca, #6366f1); border-radius: 4px 4px 0 0; }
    .castle .tower::before { content: ''; position: absolute; top: -12px; left: 50%; transform: translateX(-50%); width: 0; height: 0; border-left: 14px solid transparent; border-right: 14px solid transparent; border-bottom: 12px solid #818cf8; }
    .castle .tower:nth-child(1) { left: 0; height: 60px; }
    .castle .tower:nth-child(2) { left: 48px; height: 80px; }
    .castle .tower:nth-child(3) { right: 0; height: 60px; }
    .castle .wall { position: absolute; bottom: 0; left: 24px; right: 24px; height: 30px; background: linear-gradient(to top, #3730a3, #4338ca); }
    .firework { position: absolute; width: 6px; height: 6px; border-radius: 50%; animation: burst 2s ease-out infinite; }
    .firework:nth-child(6) { left: 40%; top: 30%; background: #f472b6; animation-delay: 0s; }
    .firework:nth-child(7) { left: 70%; top: 25%; background: #38bdf8; animation-delay: .7s; }
    .firework:nth-child(8) { left: 55%; top: 20%; background: #fbbf24; animation-delay: 1.4s; }
    @keyframes twinkle { 0% { opacity: .3; transform: scale(1); } 100% { opacity: 1; transform: scale(1.5); } }
    @keyframes burst { 0% { box-shadow: 0 0 0 0 currentColor; opacity: 1; } 100% { box-shadow: 0 0 0 20px transparent; opacity: 0; } }
    .label { margin-top: 16px; text-align: center; }
    .label h3 { color: #38bdf8; font-size: 14px; }
    .label p { color: #64748b; font-size: 12px; margin-top: 4px; }
  </style>
</head>
<body>
  <div class="stage">
    <div class="star"></div><div class="star"></div><div class="star"></div>
    <div class="star"></div><div class="star"></div>
    <div class="castle">
      <div class="tower"></div><div class="tower"></div><div class="tower"></div>
      <div class="wall"></div>
    </div>
    <div class="firework"></div><div class="firework"></div><div class="firework"></div>
  </div>
  <div class="label">
    <h3>${artifact.title}</h3>
    <p>${artifact.agentName} · ${artifact.createdAt}</p>
  </div>
</body>
</html>`
}

function artifactPlugin() {
  return {
    name: 'artifact-writer',
    configureServer(server: any) {
      // Serve artifacts as static files
      server.middlewares.use('/api/artifacts', (req: IncomingMessage, res: ServerResponse, next: Function) => {
        if (req.method === 'GET') {
          const filePath = path.join(ARTIFACTS_ROOT, req.url || '')
          if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
            const ext = path.extname(filePath)
            const mime: Record<string, string> = { '.html': 'text/html', '.tsx': 'text/plain', '.ts': 'text/plain', '.json': 'application/json', '.css': 'text/css', '.txt': 'text/plain' }
            res.writeHead(200, { 'Content-Type': mime[ext] || 'text/plain' })
            res.end(fs.readFileSync(filePath))
          } else {
            res.writeHead(404)
            res.end('Not found')
          }
        } else {
          next()
        }
      })

      // POST /api/artifacts/{taskId} — write artifacts to disk
      server.middlewares.use(async (req: IncomingMessage, res: ServerResponse, next: Function) => {
        if (req.method === 'POST' && req.url?.startsWith('/api/artifacts/')) {
          let body = ''
          req.on('data', chunk => { body += chunk })
          req.on('end', () => {
            try {
              const taskId = req.url!.replace('/api/artifacts/', '').split('/')[0]
              const data = JSON.parse(body)
              const taskDir = path.join(ARTIFACTS_ROOT, taskId)
              fs.mkdirSync(taskDir, { recursive: true })

              // Write metadata index
              const metaPath = path.join(taskDir, 'metadata.json')
              fs.writeFileSync(metaPath, JSON.stringify({
                taskId,
                taskLabel: data.taskLabel,
                moduleName: data.moduleName,
                agentName: data.agentName,
                reward: data.reward,
                hash: data.hash,
                artifacts: (data.artifacts || []).map((a: any) => ({ type: a.type, title: a.title, file: `${a.type}.${a.ext || 'txt'}` })),
                createdAt: new Date().toISOString(),
              }, null, 2))

              // Write real content files
              for (const artifact of data.artifacts || []) {
                let content: string
                switch (artifact.type) {
                  case 'preview':
                    content = generatePreviewHTML(artifact)
                    break
                  case 'source':
                    content = generateSourceTSX(artifact)
                    break
                  case 'video':
                    content = generateVideoHTML(artifact)
                    break
                  default:
                    content = JSON.stringify(artifact, null, 2)
                }
                const ext = artifact.type === 'source' ? 'tsx' : artifact.type === 'preview' || artifact.type === 'video' ? 'html' : 'txt'
                const fileName = `${artifact.type}.${ext}`
                fs.writeFileSync(path.join(taskDir, fileName), content)
              }

              res.writeHead(200, { 'Content-Type': 'application/json' })
              res.end(JSON.stringify({ ok: true, dir: taskDir }))
            } catch (err: any) {
              res.writeHead(500, { 'Content-Type': 'application/json' })
              res.end(JSON.stringify({ error: err.message }))
            }
          })
        } else {
          next()
        }
      })
    },
  }
}

export default defineConfig({
  plugins: [react(), artifactPlugin()],
  resolve: {
    alias: {
      '@marketplace': path.resolve(__dirname, '../../modules-marketplace'),
    },
    dedupe: ['react', 'react-dom', 'lucide-react'],
  },
  optimizeDeps: {
    include: ['react', 'react-dom', 'lucide-react'],
  },
  server: {
    port: 5173,
  },
})
